const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Stone: 0},
	{DropItemBomb: 0},
	{DropItemFire: 0},
	{DropItemShoes: 0},
	{FakeStone: 0},
	{BombQuantity: 0},
	{BombRange: 0},
	{ShoesVelocity: 0},
	{"8Direction": 0},
	{Player2: 0},
	{Player1: 0},
	{Keyboard: 0},
	{BombP1: 0},
	{BombP2: 0},
	{Explosion: 0},
	{WinsP1: 0},
	{WinsP2: 0},
	{ItemBomb: 0},
	{Player1Face: 0},
	{Player2Face: 0},
	{P1Bombs: 0},
	{P2Bombs: 0},
	{ItemFire: 0},
	{P1Fire: 0},
	{P2Fire: 0},
	{ItemShoes: 0},
	{P2Shoes: 0},
	{P1Shoes: 0},
	{ItemBombUI: 0},
	{ItemFireUI: 0},
	{ItemShoesUI: 0},
	{Audio: 0},
	{ButtonStart: 0},
	{PlayText: 0},
	{Mouse: 0},
	{PointsP1: 0},
	{PointsP2: 0}
];

self.InstanceType = {
	Stone: class extends self.ISpriteInstance {},
	FakeStone: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Player1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BombP1: class extends self.ISpriteInstance {},
	BombP2: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	WinsP1: class extends self.ITextInstance {},
	WinsP2: class extends self.ITextInstance {},
	ItemBomb: class extends self.ISpriteInstance {},
	Player1Face: class extends self.ISpriteInstance {},
	Player2Face: class extends self.ISpriteInstance {},
	P1Bombs: class extends self.ITextInstance {},
	P2Bombs: class extends self.ITextInstance {},
	ItemFire: class extends self.ISpriteInstance {},
	P1Fire: class extends self.ITextInstance {},
	P2Fire: class extends self.ITextInstance {},
	ItemShoes: class extends self.ISpriteInstance {},
	P2Shoes: class extends self.ITextInstance {},
	P1Shoes: class extends self.ITextInstance {},
	ItemBombUI: class extends self.ISpriteInstance {},
	ItemFireUI: class extends self.ISpriteInstance {},
	ItemShoesUI: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	PlayText: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {}
}